#ifndef CONSTANT_LIMITS_H
#define CONSTANT_LIMITS_H


#define LIMIT_UNIT_NAME 256
#define LIMIT_ENTRY_NAME 256
#define LIMIT_GROUP_NAME 256
#define LIMIT_FILE_BUFFER (1 << 16)
#define READ_WRITE_CHUNK (1 << 12)

#define LIMIT_TRACKED_UNITS 64
#define LIMIT_OBJECT_PATH 256
#define LIMIT_STATE_NAME 64



#endif // CONSTANT_LIMITS_H
